name: Build and Deploy

on:
    push:
        branches:
            - main

concurrency:
    group: deploy
    cancel-in-progress: true

jobs:
    build_deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup SSH key and known_hosts
              run: |
                  mkdir -p -m 700 ~/.ssh
                  ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                  ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"
                  ssh-keyscan ${{ secrets.DEPLOY_TARGET }} >> ~/.ssh/known_hosts
                  ssh-keyscan ${{ secrets.DEPLOY_KIT_TARGET }} >> ~/.ssh/known_hosts

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            # Set up composer caching
            - name: Cache Composer dependencies
              uses: actions/cache@v4
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            # Build Parts Kit Plugin
            - name: Build Parts Kit plugin
              run: |
                  npm ci
                  npm run build
              working-directory: wp-content/plugins/viget-parts-kit

            # Deploy code
            - name: Deploy Sandbox
              run: |

                  ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_TARGET }} "\
                    sudo chown -R ${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_DAEMON }} ${{ secrets.APP_PATH }}/wp-content &&\
                    sudo rm -rf ${{ secrets.APP_PATH }}/wp-content/plugins/viget-parts-kit &&\
                  rsync -rlptzv --exclude="node_modules" ./wp-content/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_TARGET }}:${{ secrets.APP_PATH }}/wp-content/
                  ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_TARGET }} "\
                    sudo chown -R ${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_DAEMON }} ${{ secrets.APP_PATH }}/wp-content &&\
                    sudo chown -R ${{ secrets.DEPLOY_DAEMON }}:${{ secrets.DEPLOY_DAEMON }} ${{ secrets.APP_PATH }}/wp-content/plugins"

            - name: Deploy Parts Kit
              run: |

                  ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_KIT_TARGET }} "\
                    sudo chown -R ${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_DAEMON }} ${{ secrets.APP_PATH }}/wp-content &&\
                    sudo rm -rf ${{ secrets.APP_PATH }}/wp-content/plugins/viget-parts-kit &&\
                  rsync -rlptzv --exclude="node_modules" ./wp-content/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_KIT_TARGET }}:${{ secrets.APP_PATH }}/wp-content/
                  ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_KIT_TARGET }} "\
                    sudo chown -R ${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_DAEMON }} ${{ secrets.APP_PATH }}/wp-content &&\
                    sudo chown -R ${{ secrets.DEPLOY_DAEMON }}:${{ secrets.DEPLOY_DAEMON }} ${{ secrets.APP_PATH }}/wp-content/plugins"
